version: '3.4'

services:
  todo-app-api:
    image: digitalbookstore-app-api
    container_name: digitalbookstore-app-api 
    build:
      context: ./DigitalBookstore.WebApi
      dockerfile: Dockerfile
    ports:
      - "8980:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge